### ISSUE TITLE
Functions Exercises - testPrimeRec doesn't work for 2

### ISSUE THREAD

**Issue by l-j-peacock** [rockthejvm/kotlin-essentials#1]
Whilst going through the functions exercises video I tried out 2 as a prime number and noticed that the recursive version doesn't recognise 2 as a prime number:

https://github.com/rockthejvm/kotlin-essentials/blob/e4fce1a92163554349407427a96937e0ceabb0f5/src/main/kotlin/com/rockthejvm/basics/Functions.kt#L141

I added a simple branch at the top of the if statement to fix:
if (n == 2) true

**Comment by daniel-ciocirlan** [comment]
Thanks - fixed!
